name: 'Updates Release'
description: 'Updates release.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  id:
    description: 'Id or tag of release.'
    required: true
  name:
    description: 'Name of release.'
    required: false
  body:
    description: 'Body of release.'
    required: false
  commitish:
    description: 'Target commitish of release.'
    default: master
    required: false
  draft:
    description: 'Determines whether to make release as draft.'
    required: false
  prerelease:
    description: 'Determines whether to make release as prerelease.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
