name: 'Updates Release'
description: 'Updates release.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
